version: "3"

services:
  konfigurator:
    container_name: konfigurator
    image: quay.io/mkdevops/konfigurator
    environment:
      - DATABASE_URL=/data/konfigurator.db
      - OAUTH2_ISSUER=https://mkdevops.eu.auth0.com/
      - OAUTH2_AUDIENCE=https://konfigurator.mkdevops.se/
      - OAUTH2_SIGNING_SECRET=1X****************************ZA
      - OAUTH2_SIGNING_ALGORITHM=HS256
    ports:
      - "3000:3000"
    volumes:
      - $PWD/data:/data
